### ISSUE TITLE
Syntax Error in get-token.sh

### ISSUE THREAD

**Issue by jshirle2** [grahampugh/multitenant-jamf-tools#1]
Hello, 

I am trying to use the jocads.sh script to keep our test instance in sync with our prod instance. I started by creating a prd.txt file containing the urls of these two instances. I then ran the set-credentials.sh script and get the following error: 

> get-token.sh: line 90: syntax error near unexepcted token `<'
> get-token.sh: line 90: `             done < <(find "$instance_lists_folder" -type f -name "*.txt" -print0)'

> set-credentials.sh: line 37: choose_instance_list: command not found
> Enter username for 
> User:

Any assistance would be appreciated as I am very excited to leverage this script in our environment.

**Comment by grahampugh** [comment]
Hey there, bear in mind that you need the complete folder structure in place, because all of the other scripts all source the script `get_token.sh` directly. 

And `prd.txt` must be in the `instance-lists` folder.

I did find an error in `set-credentials.sh `which I am going to push a fix for now.

**Comment by grahampugh** [comment]
should now be fixed (works for me)
